### PR TITLE
Shortcut to publishing.

### PR DESCRIPTION
**Pull request by tokejepsen**
**Implementation**

The shortcut is "Ctrl+Alt+P" which is in alignment with the shortcut in NukeStudio.

### CODE REVIEW

**Comment by mottosso** [comment]
Spontaneously, this struck me as CTRL+ALT+DEL. In a rush, I think my muscle memory might accidentally press that instead of this.

Would recommend ALT+P or CTRL+SHIFT+P. Maybe align it with whatever the common key is for "print" as it achieves similar goals and could safely hook into existing muscle memory. But it's no big deal.

**Comment by tokejepsen** [comment]
> Would recommend ALT+P or CTRL+SHIFT+P.

Unfortunately these are already taken in vanilla Nuke:

ALT+P > Proxy mode.
CTRL+SHIFT+P > Precomp.

**Comment by tokejepsen** [comment]
> Maybe align it with whatever the common key is for "print" as 

Not entirely sure what you mean with this? Do you have other example of programs where there is a shortcut to "print"?

**Comment by mottosso** [comment]
Sure, Google Docs for example uses CTRL+P and I'd expect most rich text editors do too. It's the kind of muscle memory you'd never trigger in a DCC and a key you'd likely never think to use on a whim. Possibly making it an available key and a good habit to hook into. Print is effectively the "publish" of rich text editing. :)

**Comment by tokejepsen** [comment]
> Sure, Google Docs for example uses CTRL+P

Ahh, I see.

I must have tested the shortcuts without looking at what I was doing on the keyboard, cause it turns out  CTRL+P is for Proxy mode. ALT+P is for "Enable Input Process".

The question is whether we should just override a shortcut?
I wouldn't say its the best thing to mess with Nuke default behavior, but CTRL+P is a good shortcut and most people I know never enable/disable proxy mode with a shortcut.

**Comment by mottosso** [comment]
How about making it an option?

```bash
$ set PYBLISH_HOTKEY=CTRL+P
```

And pass that to `QShortcut` which takes a string like the above.

**Comment by tokejepsen** [comment]
Hmm, that is an interesting idea. Let's roll with that... Will update this PR.

This could be implemented in all integrations.

**Comment by tokejepsen** [comment]
What do you think of this?

**Comment by mottosso** [comment]
Don't forget an example. Can I put `CTRL+P` in that variable, and that'd work with Nuke as-is? That'd be impressive! I would have expected you to have to parse it somehow. Translate it into Nuke-speak. Qt just happens to have a convenience class for doing that translation. http://doc.qt.io/qt-4.8/qshortcut.html#details

**Comment by tokejepsen** [comment]
> Don't forget an example

Done :)

> Can I put CTRL+P in that variable, and that'd work with Nuke as-is?

Yeah, Nuke is pretty forgiving on that front. There is no case-sensitvity.

**Comment by mottosso** [comment]
> Yeah, Nuke is pretty forgiving on that front. There is no case-sensitvity.

In that case I'd make a note of that, and preferably point to the docs that talk about what rules are available for hotkeys.

Apart from that I think it looks good!

**Comment by tokejepsen** [comment]
Ready for a merge then?

**Pull request merged**
