### PR TITLE
Fix Python 3 import error and update Qt.py

### PR DESCRIPTION
**Pull request by yanshil**
1. imp module is deprecated in python3.4. The import error actually comes from the complex logic of getting version number. 
2. The old Qt.py not woring in NukeX 13.0v1. I also tried  v1.2.5 Qt.py used in pyblish-maya, which will make the pyblish-qml gui (lite not tested) crashed. The latest one v1.3.5 is working.

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks! But that logic, oh man. The `version.py` file is very simple, how about something like this?

```py
version = []

with open("version.py") as f:
  for line in f:
     if not line.startswith("VERSION_"):
        continue

     _, v = line.rstrip().split(" = ")
     version += [v]

version = ".".join(version)
```

**Comment by yanshil** [comment]
Well, actually, I prefer directly state the version in setup.py lol, something like `version = '2.1.3'`
(Actually I am doing that in my pyblish-ue4 repo.)

I was just trying to keep the the structure of your code. Feel free to modify it :)

**Comment by mottosso** [comment]
pyblish-ue4? :O

The reason the version number is coming from that Python module is so that is accessible from Python, something that is consistent across all Pyblish libraries.

```py
import pyblish_nuke
print(pyblish_nuke.__version__)
```

You can leave it to me, but it might take me a few weeks as I'm on other projects. I'd rather not merge something this complex as it looks very difficult to debug once something goes wrong.

**Comment by yanshil** [comment]
I will submit a new version tomorrow with you code you attach above. I think it should work.

For the UE4, ahh, I just implement the add/remove menu item function, not that complex.
Especially when I left the dock functionality empty because I currently don't need that.

**Comment by yanshil** [comment]
Updated.

**Comment by mottosso** [comment]
This looks good to me, nice work!

**Pull request merged**
